# Generated by Django 5.2.3 on 2025-06-22 16:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("biography", models.TextField(blank=True)),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "place_of_birth",
                    models.CharField(default="Unknown", max_length=255, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("0", "Not specified"),
                            ("1", "Female"),
                            ("2", "Male"),
                            ("3", "Non-binary"),
                        ],
                        default="0",
                        max_length=10,
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("adult", models.BooleanField(default=False)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("Bad", "Bad"),
                            ("Average", "Average"),
                            ("Good", "Good"),
                            ("Excellent", "Excellent"),
                        ],
                        default="Good",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Post Production", "Post Production"),
                            ("Released", "Released"),
                        ],
                        default="Planned",
                        max_length=15,
                    ),
                ),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("box_office", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="films",
                        to="manage_movies.author",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="films",
                        to="manage_movies.genre",
                        verbose_name="Genres",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1–5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "spectator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Spectator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notation",
                "verbose_name_plural": "Notations",
                "ordering": ["-created_at"],
                "unique_together": {("spectator", "content_type", "object_id")},
            },
        ),
    ]
