# Generated by Django 5.2.3 on 2025-06-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("manage_movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("model__in", ["film", "author"])),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
