# Generated by Django 5.2.3 on 2025-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_movies", "0002_author_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="death_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="gender",
            field=models.CharField(
                choices=[
                    ("0", "Not specified"),
                    ("1", "Female"),
                    ("2", "Male"),
                    ("3", "Non-binary"),
                ],
                default="0",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="place_of_birth",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="film",
            name="adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="film",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("post Production", "Post Production"),
                    ("released", "Released"),
                ],
                default="planned",
                max_length=15,
            ),
        ),
    ]
