# Generated by Django 5.2.3 on 2025-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_movies", "0002_alter_film_box_office_alter_film_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="author",
        ),
        migrations.AddField(
            model_name="film",
            name="authors",
            field=models.ManyToManyField(
                related_name="films", to="manage_movies.author"
            ),
        ),
    ]
