# Generated by Django 5.2.3 on 2025-06-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_movies", "0003_genre_author_biography_author_death_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spectator",
            options={"verbose_name": "Spectator", "verbose_name_plural": "Spectators"},
        ),
        migrations.AlterField(
            model_name="film",
            name="box_office",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
