# Generated by Django 5.2.3 on 2025-06-22 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manage_movies",
            "0004_alter_spectator_options_alter_film_box_office_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="spectator",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="manage_movies.film",
                verbose_name="Films favoris",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.CharField(
                choices=[
                    ("Bad", "Bad"),
                    ("Average", "Average"),
                    ("Good", "Good"),
                    ("Excellent", "Excellent"),
                ],
                default="Good",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("Post Production", "Post Production"),
                    ("Released", "Released"),
                ],
                default="Planned",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1–5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="manage_movies.film",
                        verbose_name="Film",
                    ),
                ),
                (
                    "spectator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Spectateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notation",
                "verbose_name_plural": "Notations",
                "ordering": ["-created_at"],
                "unique_together": {("spectator", "film")},
            },
        ),
    ]
